alter table JOKERHACCP_CONTACT add constraint FK_JOKERHACCP_CONTACT_ON_SUPPLIER foreign key (SUPPLIER_ID) references JOKERHACCP_SUPPLIER(ID);
create index IDX_JOKERHACCP_CONTACT_ON_SUPPLIER on JOKERHACCP_CONTACT (SUPPLIER_ID);
