alter table JOKERHACCP_PURCHASE add constraint FK_JOKERHACCP_PURCHASE_ON_PRODUCT foreign key (PRODUCT_ID) references JOKERHACCP_PRODUCT(ID);
alter table JOKERHACCP_PURCHASE add constraint FK_JOKERHACCP_PURCHASE_ON_SUPPLIER foreign key (SUPPLIER_ID) references JOKERHACCP_SUPPLIER(ID);
create index IDX_JOKERHACCP_PURCHASE_ON_PRODUCT on JOKERHACCP_PURCHASE (PRODUCT_ID);
create index IDX_JOKERHACCP_PURCHASE_ON_SUPPLIER on JOKERHACCP_PURCHASE (SUPPLIER_ID);
